version: "3.8"
services:
    client:
        container_name: jetbrains_frontend
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3001:3000
        volumes:
            - "/app/node_modules"
            - "./:/app"
